### ISSUE TITLE
CUB link not working

### ISSUE THREAD

**Issue by SinghJasdeep** [tristandeleu/pytorch-meta#104]
Get following trace when using CUB: 

```
Downloading http://www.vision.caltech.edu/visipedia-data/CUB-200-2011/CUB_200_2011.tgz to /home/jasdeep/data/cub/CUB_200_2011.tgz
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "Projecting-Conflicting-Gradients/multi_train.py", line 179, in <module>
    main(args)
  File "Projecting-Conflicting-Gradients/multi_train.py", line 44, in main
    hidden_size=args.hidden_size)
  File "/home/jasdeep/Projecting-Conflicting-Gradients/maml/multi_datasets.py", line 69, in get_benchmark_by_name_1
    download=True))
  File "/home/jasdeep/venv/lib/python3.7/site-packages/torchmeta/datasets/cub.py", line 95, in __init__
    class_augmentations=class_augmentations, download=download)
  File "/home/jasdeep/venv/lib/python3.7/site-packages/torchmeta/datasets/cub.py", line 129, in __init__
    self.download()
  File "/home/jasdeep/venv/lib/python3.7/site-packages/torchmeta/datasets/cub.py", line 182, in download
    download_url(self.download_url, self.root, filename, self.tgz_md5)
  File "/home/jasdeep/venv/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 86, in download_url
    raise RuntimeError("File not found or corrupted.")
RuntimeError: File not found or corrupted.
73728it [00:00, 165960.03it/s]
```

Is resolved if I manually download CUB_200_2011.tgz from another source. 
Might be a temporary thing

**Comment by tristandeleu** [comment]
It seems that they indeed changed the host for the CUB dataset (now the url redirects to Google Drive). I'll make the change to `CUB` to download the dataset from Google Drive.
