### ISSUE TITLE
Mini-ImageNet download broken?

### ISSUE THREAD

**Issue by carmete** [tristandeleu/pytorch-meta#54]
Running:
```python
from torchmeta.datasets.helpers import miniimagenet
dataset = miniimagenet("data", ways=5, shots=5, test_shots=15, meta_train=True, download=True)
```
throws the following error:
```
3089it [00:00, 1760353.95it/s]
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    dataset = miniimagenet("data", ways=5, shots=5, test_shots=15, meta_train=True, download=True)
  File ".../pytorch-meta/torchmeta/datasets/helpers.py", line 126, in miniimagenet
    seed=seed, defaults=defaults, **kwargs)
  File ".../pytorch-meta/torchmeta/datasets/helpers.py", line 34, in helper_with_default
    dataset = klass(folder, num_classes_per_task=ways, **kwargs)
  File ".../pytorch-meta/torchmeta/datasets/miniimagenet.py", line 89, in __init__
    download=download)
  File ".../pytorch-meta/torchmeta/datasets/miniimagenet.py", line 124, in __init__
    self.download()
  File ".../pytorch-meta/torchmeta/datasets/miniimagenet.py", line 178, in download
    with tarfile.open(filename, 'r') as f:
  File "/usr/lib/python3.6/tarfile.py", line 1576, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
````

A file `data/miniimagenet/mini-imagenet.tar.gz` is created, but only of size 3.1kB, instead of the expected 1.1GB.

Downloading the data directly from https://github.com/renmengye/few-shot-ssl-public works fine.

**Comment by tristandeleu** [comment]
I am not able to reproduce this issue right now, I can download the dataset with the example you gave. However I have seen this issue in the past trying to download TieredImagenet with Torchmeta (MiniImagenet worked fine). My assumption is that the utility function `download_file_from_google_drive` from Torchvision sometimes fails the authentication on Google Drive.

The temporary solution if this happens is indeed to manually download the data and placing it in your data folder, but this is an inconvenience. If you could add the 3.1kB file that gets downloaded here (which is likely to be an HTML file), I will open an issue on Torchvision so that they can have a look at it. Thanks!

**Comment by carmete** [comment]
The problem doesn't persist on my end either. So yes, it seems to be a temporary issue. Here is the file, that was downloaded:
[mini-imagenet.tar.gz](https://github.com/tristandeleu/pytorch-meta/files/4771773/mini-imagenet.tar.gz)

**Comment by tristandeleu** [comment]
Thank you for the file. It looks like this is not due to an authentication problem, but because of quotas on Google Drive.

>Google Drive - Quota exceeded
>
>Sorry, you can't view or download this file at this time.
>Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

**Comment by brando90** [comment]
@tristandeleu I get a data integrity issue...what does that mean? Do I download it again or what do you recommend?

```
    raise RuntimeError('MiniImagenet integrity check failed')
```

**Comment by tristandeleu** [comment]
Integrity issue here indeed means a quota issue on Google Drive's end. This is unfortunately out of our control, and the best thing to do is to wait for the quota to be reset.

**Comment by brando90** [comment]
what does "Integrity issue here indeed means a quota issue on Google Drive's end" mean?

**Comment by tristandeleu** [comment]
The error you get `MiniImagenet integrity check failed` is caused by the [quota of Google Drive](https://support.google.com/a/answer/7338880?hl=en) being reached.
